// Схема хранилища учётных записей. Держится в одном месте и в двух диалектах:
// всё, кроме объявления таблиц, написано так, чтобы работать в обоих —
// параметры вида $1, ON CONFLICT, RETURNING, время строкой ISO-8601.
//
// Время намеренно хранится текстом, а не timestamptz: весь остальной код
// проекта оперирует new Date().toISOString(), и перевод на родной тип
// PostgreSQL означал бы, что одни и те же поля приходят то строкой, то
// объектом Date, в зависимости от того, где выполнен запрос. Сравнение и
// сортировка ISO-8601 в UTC совпадают с лексикографическими, поэтому ничего
// не теряется.
//
// Логические признаки (is_active, must_change_password) хранятся как INTEGER
// 0/1, а не BOOLEAN, по той же причине: весь код сравнивает их с 1.

const DDL = {
  postgres: `
    CREATE TABLE IF NOT EXISTS roles (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL UNIQUE,
      description TEXT,
      permissions_json TEXT NOT NULL
    );

    CREATE TABLE IF NOT EXISTS departments (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      parent_id INTEGER REFERENCES departments(id) ON DELETE SET NULL,
      name TEXT NOT NULL,
      description TEXT,
      dept_type TEXT DEFAULT 'department',
      sort_order INTEGER DEFAULT 0,
      created_at TEXT NOT NULL
    );

    CREATE TABLE IF NOT EXISTS users (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      username TEXT NOT NULL UNIQUE,
      password_hash TEXT NOT NULL,
      salt TEXT,
      full_name TEXT NOT NULL,
      email TEXT,
      phone TEXT,
      job_title TEXT,
      department_id INTEGER REFERENCES departments(id) ON DELETE SET NULL,
      role_id INTEGER REFERENCES roles(id) ON DELETE SET NULL,
      admin_scope_dept_id INTEGER REFERENCES departments(id) ON DELETE SET NULL,
      avatar_url TEXT,
      status TEXT DEFAULT 'offline',
      custom_status TEXT,
      uin INTEGER,
      extension TEXT,
      company TEXT,
      bound_ip TEXT,
      last_seen TEXT,
      is_active INTEGER NOT NULL DEFAULT 1,
      must_change_password INTEGER NOT NULL DEFAULT 0,
      approval_status TEXT NOT NULL DEFAULT 'approved',
      registered_at TEXT,
      created_at TEXT NOT NULL,
      token_version INTEGER NOT NULL DEFAULT 1,
      password_changed_at TEXT,
      failed_login_count INTEGER NOT NULL DEFAULT 0,
      locked_until TEXT,
      last_login_at TEXT,
      last_login_ip TEXT
    );

    CREATE INDEX IF NOT EXISTS idx_users_department ON users(department_id);
    CREATE INDEX IF NOT EXISTS idx_users_approval ON users(approval_status);

    CREATE TABLE IF NOT EXISTS pending_devices (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      device_id TEXT NOT NULL UNIQUE,
      device_name TEXT,
      ip_address TEXT,
      platform TEXT,
      client_version TEXT,
      status TEXT DEFAULT 'pending',
      first_knock_at TEXT NOT NULL,
      last_knock_at TEXT NOT NULL
    );

    CREATE TABLE IF NOT EXISTS device_pairings (
      device_id TEXT PRIMARY KEY,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      ip_address TEXT,
      device_name TEXT,
      paired_at TEXT NOT NULL,
      is_active INTEGER NOT NULL DEFAULT 1,
      secret_hash TEXT,
      secret_token_version INTEGER
    );

    CREATE TABLE IF NOT EXISTS audit_logs (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
      action TEXT NOT NULL,
      details_json TEXT,
      ip_address TEXT,
      created_at TEXT NOT NULL
    );

    CREATE INDEX IF NOT EXISTS idx_audit_action ON audit_logs(action);

    CREATE TABLE IF NOT EXISTS server_settings (
      key TEXT PRIMARY KEY,
      value TEXT NOT NULL,
      updated_at TEXT NOT NULL
    );
  `,

  sqlite: `
    CREATE TABLE IF NOT EXISTS roles (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      name TEXT NOT NULL UNIQUE,
      description TEXT,
      permissions_json TEXT NOT NULL
    );

    CREATE TABLE IF NOT EXISTS departments (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      parent_id INTEGER REFERENCES departments(id) ON DELETE SET NULL,
      name TEXT NOT NULL,
      description TEXT,
      dept_type TEXT DEFAULT 'department',
      sort_order INTEGER DEFAULT 0,
      created_at TEXT NOT NULL
    );

    CREATE TABLE IF NOT EXISTS users (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      username TEXT NOT NULL UNIQUE,
      password_hash TEXT NOT NULL,
      salt TEXT,
      full_name TEXT NOT NULL,
      email TEXT,
      phone TEXT,
      job_title TEXT,
      department_id INTEGER REFERENCES departments(id) ON DELETE SET NULL,
      role_id INTEGER REFERENCES roles(id) ON DELETE SET NULL,
      admin_scope_dept_id INTEGER REFERENCES departments(id) ON DELETE SET NULL,
      avatar_url TEXT,
      status TEXT DEFAULT 'offline',
      custom_status TEXT,
      uin INTEGER,
      extension TEXT,
      company TEXT,
      bound_ip TEXT,
      last_seen TEXT,
      is_active INTEGER NOT NULL DEFAULT 1,
      must_change_password INTEGER NOT NULL DEFAULT 0,
      approval_status TEXT NOT NULL DEFAULT 'approved',
      registered_at TEXT,
      created_at TEXT NOT NULL,
      token_version INTEGER NOT NULL DEFAULT 1,
      password_changed_at TEXT,
      failed_login_count INTEGER NOT NULL DEFAULT 0,
      locked_until TEXT,
      last_login_at TEXT,
      last_login_ip TEXT
    );

    CREATE INDEX IF NOT EXISTS idx_users_department ON users(department_id);
    CREATE INDEX IF NOT EXISTS idx_users_approval ON users(approval_status);

    CREATE TABLE IF NOT EXISTS pending_devices (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      device_id TEXT NOT NULL UNIQUE,
      device_name TEXT,
      ip_address TEXT,
      platform TEXT,
      client_version TEXT,
      status TEXT DEFAULT 'pending',
      first_knock_at TEXT NOT NULL,
      last_knock_at TEXT NOT NULL
    );

    CREATE TABLE IF NOT EXISTS device_pairings (
      device_id TEXT PRIMARY KEY,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      ip_address TEXT,
      device_name TEXT,
      paired_at TEXT NOT NULL,
      is_active INTEGER NOT NULL DEFAULT 1,
      secret_hash TEXT,
      secret_token_version INTEGER
    );

    CREATE TABLE IF NOT EXISTS audit_logs (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
      action TEXT NOT NULL,
      details_json TEXT,
      ip_address TEXT,
      created_at TEXT NOT NULL
    );

    CREATE INDEX IF NOT EXISTS idx_audit_action ON audit_logs(action);

    CREATE TABLE IF NOT EXISTS server_settings (
      key TEXT PRIMARY KEY,
      value TEXT NOT NULL,
      updated_at TEXT NOT NULL
    );
  `
};

// Таблицы с собственным счётчиком id. После переноса готовых строк счётчик
// надо подвинуть за наибольший занятый id, иначе первая же новая запись
// столкнётся с существующей.
const SEQUENCED_TABLES = ['roles', 'departments', 'users', 'pending_devices', 'audit_logs'];

// Колонки, появившиеся после первого выпуска. CREATE TABLE IF NOT EXISTS
// существующую таблицу не трогает, поэтому их добавляет отдельный шаг.
const ADDED_COLUMNS = [
  // Секрет устройства: вход без пароля возможен, только если клиент его
  // предъявил. Номер устройства сам по себе больше не пропуск.
  ['device_pairings', 'secret_hash', 'TEXT'],
  ['device_pairings', 'secret_token_version', 'INTEGER']
];

async function columnsOf(driver, table) {
  if (driver.dialect === 'postgres') {
    const rows = await driver.all(
      'SELECT column_name AS name FROM information_schema.columns WHERE table_name = $1',
      [table]
    );
    return new Set(rows.map((r) => r.name));
  }
  const rows = await driver.all(`PRAGMA table_info(${table})`);
  return new Set(rows.map((r) => r.name));
}

async function createSchema(driver) {
  await driver.exec(DDL[driver.dialect]);
  for (const [table, column, type] of ADDED_COLUMNS) {
    const existing = await columnsOf(driver, table);
    if (!existing.has(column)) await driver.exec(`ALTER TABLE ${table} ADD COLUMN ${column} ${type}`);
  }
}

async function resyncSequences(driver) {
  if (driver.dialect !== 'postgres') return; // SQLite ведёт счётчик сам
  for (const table of SEQUENCED_TABLES) {
    const row = await driver.get(`SELECT COALESCE(MAX(id), 0) + 1 AS next FROM ${table}`);
    const next = Number(row?.next || 1);
    await driver.exec(`ALTER TABLE ${table} ALTER COLUMN id RESTART WITH ${next}`);
  }
}

module.exports = { DDL, SEQUENCED_TABLES, createSchema, resyncSequences };
